Digimon_TCG_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_json, show_json_by_id, show_xml, show_xml_by_id, register, login_user, logout_user, show_main_by_id, delete_item, increment_amount, decrement_amount, edit_item, get_item_json, add_item_ajax, delete_item_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('<int:id>/', show_main_by_id, name='show_main_by_id'),
    path('', show_main, name='show_main'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('create-item/', create_item, name='create_item'),
    path('increment-amount/<int:id>', increment_amount, name='increment_amount'),
    path('decrement-amount/<int:id>', decrement_amount, name='decrement_amount'),
    path('delete-item/<int:id>', delete_item, name='delete_item'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('xml/', show_xml, name= 'show_xml'),
    path('json/', show_json, name = 'show_json'),
    path('xml/<int:id>/', show_xml_by_id, name= 'show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name= 'show_json_by_id'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_ajax'),
    path('delete-ajax/<int:id>', delete_item_ajax, name='delete_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    category = models.CharField(max_length= 225)
    code = models.CharField(max_length= 225)
    amount = models.IntegerField()
    price = models.FloatField()
    description = models.TextField()
    date_added = models.DateField(default=datetime.date(2023,9,15))
    COLOR_CHOICES = [
        ("Blue", "Blue"),
        ("Red", "Red"),
        ("Green", "Green"),
        ("Yellow", "Yellow"),
        ("Purple", "Purple"),
        ("Black", "Black"),
        ("White", "White")
    ]
    color = models.CharField(max_length=11, choices=COLOR_CHOICES)
    rarity = models.CharField(max_length = 3, default='R')

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "category", "code", "amount", "price", "description", "color", "rarity"]

main/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from main.forms import ItemForm
from main.models import Item
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    context = {
        'name' : request.user.username,
        'class' : 'PBP KKI',
        'items' : items,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'main.html', context)

def show_main_by_id(request, id):
    items = Item.objects.filter(user=request.user)
    id_item = Item.objects.filter(user=request.user).get(pk=id)
    context = {
        'name' : request.user.username,
        'class' : 'PBP KKI',
        'items' : items,
        'item': id_item,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'main_id.html', context)


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'name' : request.user.username,
        'form': form}
    return render(request, "create_item.html", context)

def delete_item(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def increment_amount(request, id):
    item = Item.objects.get(pk = id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrement_amount(request, id):
    item = Item.objects.get(pk = id)
    if item.amount>0:
        item.amount -= 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    product = Item.objects.get(pk = id)

    form = ItemForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'name' : request.user.username,
        'form': form}
    return render(request, "edit_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_item_json(request):
    item = Item.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        category = request.POST.get("category")
        code = request.POST.get("code")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        description = request.POST.get("description")
        color = request.POST.get("color")
        date_added = datetime.datetime.now()
        user = request.user

        new_item = Item(name=name, category=category, code=code, amount=amount, price=price, description=description, color = color, date_added = date_added,user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, id):
    if request.method == 'POST':
        item = Item.objects.get(pk = id)
        item.delete()
        return HttpResponse(b"DELETED", status = 201)
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            category = data["category"],
            code = data["code"],
            amount = int(data["amount"]),
            date_added = datetime.datetime.now(),
            color = data["color"] 
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% load widget_tweaks %}
 
{% block content %}
<body style = "background-color: gray;"></body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" style = "margin: 0; padding: 0;">
    <div class="container-fluid" style = "background-color: dimgray; padding-right: 0;">
        <a class="navbar-brand" href="{% url 'main:show_main' %}" style = "color: aliceblue;">{{ name }}</a>
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-primary btn-lg">Logout</button>
        </a>
    </div>
</nav>
<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <div class="grid-container">
        <div class="form-group">
            <p style = "font-weight: bold;"> Name: </p>
            {% render_field form.name class="form-control" placeholder="Agumon" type="text" %}
        </div>
        <div class="form-group">
            <p style = "font-weight: bold;"> Category: </p>
           {% render_field form.category type="text" class="form-control" placeholder="Lv.3 Digimon" %}
         </div>
         <div class="form-group">
            <p style = "font-weight: bold;"> Code: </p>
           {% render_field form.code type="text" class="form-control" placeholder="RB1-004" %}
         </div>
    </div>
    <div class = "grid-container1" style = "padding-top: 5px">
        <div class="form-group">
            <p style = "font-weight: bold;"> Description: </p>
            {% render_field form.description class="form-control" placeholder="A cool card" type="text" %}
        </div>
        <div class = "form-group">
            <p style = "font-weight: bold; "> Color: </p>
            {% render_field form.color class="form-control" type="text" %}
            <p style = "font-weight: bold;"> Price: </p>
            {% render_field form.price class="form-control" placeholder="24.99" type="text" %}
            <p style = "font-weight: bold;"> Amount: </p>
            {% render_field form.amount class="form-control" placeholder="2" type="text" %}
            <button class = "btn btn-primary btn-lg"type="submit" value="Add Item" style = "margin-top: 15px" > Add Item </button>
        </div>
    </div>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<body style = "background-color: gray"></body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" style = "margin: 0; padding: 0;">
    <div class="container-fluid" style = "background-color: dimgray; padding-right: 0;">
        <a class="navbar-brand" href="{% url 'main:show_main' %}" style = "color: aliceblue;">{{ name }}</a>
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-primary btn-lg">Logout</button>
        </a>
    </div>
</nav>
<h1>Edit Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% load static %}
<body id="bg" style="background-image: url('{%static 'assets/Digimon_Card_Game_main.png'%}') ;">
</body>
<div class = "container min-vh-100 d-flex justify-content-end" style = "padding-right: 0%; margin-right: 0%; height: 100vh; background-color: white;width: 30%;">
    <div class = "login align-self-center">

        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                    
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn btn-primary" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        <br>
        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style = "margin: 0; padding: 0;">
        <div class="container-fluid" style = "background-color: dimgray; padding-right: 0;">
            <a class="navbar-brand" href="#" style = "color: aliceblue;">{{ name }}</a>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-primary btn-lg">Logout</button>
            </a>
        </div>
    </nav>
    <h5>Class:</h5>
    <p>{{ class }}</p>
    <br>

    <a href="/get-item/R" style = "text-decoration: none;">
        <button onclick="filterRarity()" class = "btn btn-outline-secondary">
            Filter R
        </button>
    </a>

    <table id = "item_table" class="table table-striped table-hover"></table>
    
    <br />
    <h5>Last login session: {{ last_login }}</h5>
    <br>
    
    <a href="{% url 'main:create_item' %}" style = "text-decoration: none;">
        <button class = "btn btn-outline-success">
            Add New Item
        </button>
    </a>

    <a href="{% url 'main:logout' %}" style = "text-decoration: none;">
        <button class = "btn btn-outline-secondary">
            Logout
        </button>
    </a>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="col-form-label">Category:</label>
                            <input type="text" class="form-control" id="category" name="category"></input>
                        </div>
                        <div class="mb-3">
                            <label for="code" class="col-form-label">Code:</label>
                            <input type="text" class="form-control" id="code" name="code"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="color" class="col-form-label">Color:</label>
                            <select class="form-control" id="color" name="color">
                                <option value="Blue">Select Color</option>
                                <option value="Blue">Blue</option>
                                <option value="Red">Red</option>
                                <option value="Green">Green</option>
                                <option value="Yellow">Yellow</option>
                                <option value="Purple">Purple</option>
                                <option value="Black">Black</option>
                                <option value="White">White</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="rarity" class="col-form-label">Rarity:</label>
                            <input type="text" class="form-control" id="rarity" name="rarity"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }
        async function refreshItems(Prarity = 'All') {
            document.getElementById("item_table").innerHTML = ""
            const items = await getItems()
            let htmlString = `<tr>
                <th>Code</th>
                <th>Name</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Rarity</th>
                <th>Date Added</th>
                <th></th>
            </tr>`
            items.forEach((item) => {
                if (Prarity ='All' or item.fields.rarity == Prarity){
                htmlString += `\n<tr>
                <td> <a href="/${item.pk}">${item.fields.code}</a></td>
                <td>${item.fields.name}</td>
                <td>${item.fields.price}</td>
                <td>
                    <a href="/increment-amount/${item.pk}" style=" text-decoration: none;">
                        <button class = inc-btn>
                            +
                        </button>
                    </a>
                    ${item.fields.amount}
                    <a href="/decrement-amount/${item.pk}">
                        <button class = "dec-btn">
                            - 
                        </button>
                    </a>
                </td>
                <td>${item.fields.rarity}</td>
                <td>${item.fields.date_added}</td>
                <td>
                    <button onclick="deleteItem(${item.pk})" class = "btn btn-danger del-btn" style = "padding-top: 5px; padding-bottom: 5px;">
                        Delete
                    </button>
                    <a href="/edit-item/${item.pk}">
                        <button class = "btn btn-info" style = "padding-top: 5px; padding-bottom: 5px;">
                            Edit
                        </button>
                    </a>
                </td>
            </tr>` 
        }
        })
        
        document.getElementById("item_table").innerHTML = htmlString
    }

    function addItem() {
        fetch("{% url 'main:add_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }

    function deleteItem(id){
        fetch("/delete-ajax/"+ id, {
            method: "POST",
        }).then(refreshItems)

        return false
    }
    document.getElementById("button_add").onclick = addItem
    refreshItems()
    </script>
    
{% endblock content %}

main/templates/main_id.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style = "margin: 0; padding: 0;">
        <div class="container-fluid" style = "background-color: dimgray; padding-right: 0;">
            <a class="navbar-brand" href="{% url 'main:show_main' %}" style = "color: aliceblue;">{{ name }}</a>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-primary btn-lg">Logout</button>
            </a>
        </div>
    </nav>
    <h5>Class:</h5>
    <p>{{ class }}</p>
    <br>
    <p>This is a work in progress. Here is info about {{ item.name }}</p>
    <br>
    {% if item.color == "Black"%}
    <div class = "container card d-flex justify-content-center" style = "padding: 1%;width: 500px; background-color: lightgrey">
    {% elif item.color == "Purple"%}
    <div class = "container card d-flex justify-content-center" style = "padding: 1%;width: 500px; background-color: #E0B0FF">
    {% elif item.color == "Red"%}
    <div class = "container card d-flex justify-content-center" style = "padding: 1%;width: 500px; background-color: #FFCCCB">
    {% else %}
    <div class = "container card d-flex justify-content-center" style = "padding: 1%;width: 500px; background-color: light{{item.color}}">
    {% endif %}
        <img class="card-img-top" src="{% static 'assets/' %}{{item.code}}.webp" alt="{{item.name}}">
        <div class="card-body">
            <h5 class = "card-title" style = "font-weight: bold;">{{ item.name }}</h5>
            <p class = "card-text"> <span style = "font-weight: bold;">Color: </span>{{ item.color }}</p>
            <p class = "card-text"> <span style = "font-weight: bold;">Category: </span>{{ item.category }}</p>
            <p class = "card-text"> <span style = "font-weight: bold;">Card code:</span> {{ item.code }}</p>
            <p class = "card-text"> <span style = "font-weight: bold;">Amount in Stock:</span> {{ item.amount }}</p>
            <p class = "card-text"> <span style = "font-weight: bold;">Average listed price:</span> ${{ item.price }}</p>
            <p class = "card-text" style = "font-weight: bold;">Description:</p>
            <p class = "card-text">{{ item.description }}</p>
        </div>
    </div>
    
    <a href="{% url 'main:show_main' %}">
        <button class = "btn btn-primary">
            Home
        </button>
    </a>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
{% load static %}
<body id="bg1" style="background-image: url('{%static 'assets/Digimon_Card_Game_main.png'%}') ;">
</body>
<div class = "container min-vh-100 d-flex justify-content-end" style = "padding-right: 0%; margin-right: 0%; height: 100vh; background-color: lightgray;width: 40%;">
    <div class = "login align-self-center">
        <h1>Register</h1>  
        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" class = "btn btn-primary"></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}
    </div>
</div>  

{% endblock content %}